### DISCUSSION TITLE
add placeholder type list

### DISCUSSION THREAD

**Discussion by Zarkness2** [itsme-to/ItsMyConfig#7] [Ideas]
the placeholder of type list would be placeholder which would have a list inside example
```yml
  example:
    values:
    - "value 1"
    - "value 2"
    - "value 3"
    - "value 4"
    type: list
```

and they would be called like this `%itsmyconfig_example_list_<position>%`

where position would be the place of the text in this example to call the message value 4 would be with %itsmyconfig_example_list_4% and would return value 4 if you change the 4 by 2 would return value 2
